import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNavBar from "@/components/TopNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopNavBar />
        {children}
      </body>
      <a href="https://www.freepik.com/free-vector/doctors-personalized-prescriptive-analytics_11667703.htm#fromView=search&page=3&position=27&uuid=c2a7f059-5fed-4ece-a217-92e9507dce02">
        Image by vectorjuice
      </a>{" "}
      on Freepik
    </html>
  );
}
